<?php foreach ($cats->items as $cat) { ?>
	<?php 	$catId = $cat->id;
		  	$catName = $cat->cattitle;
		  	$catDescription = $cat->description;
		?>
	<div class="am-cf am-g am-margin-bottom-xs">
		<div class="am-u-lg-1 am-show-lg-only"><?php echo $catId ?></div>
		<div class="am-u-lg-2 am-u-md-6 am-u-sm-6"><?php echo $catName ?></div>
		<div class="am-u-lg-6 am-show-lg-only am-text-truncate"><?php echo $catDescription ?></div>
		<div class="am-u-lg-3 am-u-md-6 am-u-sm-6 am-g-collapse">
			<div class="am-u-lg-6 am-u-md-6 am-u-sm-6">
				<a href="#" class="am-btn am-btn-success am-btn-block am-btn-xs cat-update" catid="<?php echo $catId ?>">编辑</a>
			</div>
			<div class="am-u-lg-6 am-u-md-6 am-u-sm-6">
				<a href="#" class="am-btn am-btn-warning am-btn-block am-btn-xs cat-delete" catid="<?php echo $catId ?>">删除</a>
			</div>
		</div>
	</div>
<?php } ?>
		
  	<hr/>

  	<div class="pagenavi">
		<?php
	  		$current = $cats->current;
	        $before = $cats->before;
	        $next = $cats->next;
	        $last = $cats->last;
	        $total_pages = $cats->total_pages;
	        $total_items = $cats->total_items;
	        ?>
  		<?php if ($current != 1) { ?>
  			<a href="#" id="cat-index-page">首页</a>
		<?php } ?>

  		<?php if ($before != $current) { ?>
  			<a href="#" id="cat-prev-page" page="<?php echo $before ?>">上一页</a>
  		<?php } ?>

  		<span class="current-nav" id="cat-current-page" page="<?php echo $current ?>"><?php echo $current ?></span>
  		
  		<?php if ($next != $current) { ?>
  			<a href="#" id="cat-next-page" page="<?php echo $next ?>">下一页</a>
  		<?php } ?>
		
		<?php if ($last != $current) { ?>
  			<a href="#" id="cat-last-page" page="<?php echo $last ?>">末页</a>
  		<?php } ?>
  		
  		<a>共 <?php echo $total_pages ?> 页</a>
  		<a><?php echo $total_items ?> 个分类</a>
  	</div>