<?php 
	echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
>
	<channel>
		<title><?php echo $this->di->get('config')->site->name ?></title>
		<atom:link href="<?php echo $this->di->get('config')->site->url ?>/feed" rel="self" type="application/rss+xml" />
		<link><?php echo $this->di->get('config')->site->url ?></link>
		<description><?php echo $this->di->get('config')->site->description ?></description>
		<lastBuildDate><?php echo $post->getFeedLastBuildDate() ?></lastBuildDate>
		<language>zh-CN</language>
		<sy:updatePeriod>hourly</sy:updatePeriod>
		<sy:updateFrequency>1</sy:updateFrequency>
		<generator><?php echo $this->di->get('config')->site->url ?></generator>
		
		<?php foreach ($posts as $postItem) { ?>
			<item>
				<title><?php echo $postItem->getPostTitle(100) ?></title>
				<link><?php echo $postItem->getPostUrl() ?></link>
				<comments><?php echo $postItem->getPostUrl() ?></comments>
				<pubDate><?php echo $postItem->getFeedPublishedDate() ?></pubDate>
				<dc:creator><![CDATA[<?php echo $postItem->getAuthor() ?>]]></dc:creator>
				<?php foreach ($postItem->getArrayPostCategory() as $postCat) { ?>
					<category><![CDATA[<?php echo $postCat ?>]]></category>
				<?php } ?>
				<description><![CDATA[<?php echo $postItem->getPostExcerpt(400) ?><a href="<?php echo $postItem->getPostUrl() ?>">继续阅读 <span class="meta-nav">&#8594;</span></a>]]></description>
				<guid><?php echo $postItem->getPostUrl() ?></guid>
			</item>
		<?php } ?>

	</channel>
</rss>