<div class="main" id="main">
	<?php echo $this->elements->getBreadCrumb($crumbName); ?>
	<div class="content">
		<article class="article">
			<?php $post->setPostView() ?>
			<div class="single-default">			
				<div class="single-default-post-title">
					<h1 class="border-left"><a href="<?php echo $post->getPostUrl() ?>"><?php echo $post->getPostTitle() ?></a></h1>
				</div>
				<div class="single-default-post-info">
					<span class="single-default-box-cat muted">
						<?php echo $post->getPublishedDate() ?>
					</span>
					<span class="single-default-box-cat muted">
						<?php echo $post->getPostView(); ?> ℃
					</span>
					<span class="single-default-box-cat muted">
						<?php echo $getPostCategoryLink = $post->getPostCategoryLink() ?>	
					</span>
					<span class="single-default-box-cat muted">
						<?php echo $getPostTagLink = $post->getPostTagLink() ?>
					</span>
				</div>
				<div class="post-content">
					<?php echo $post->getContent() ?>
				</div>
			</div>
			<div class="post-bottom">
				<div class="post-bottom-title">
					<h5 class="border-left">本文属性</h5>
				</div>
				<div class="post-detail">
					<ul>
						<li>所属分类：<span id="post_category"> 
							<?php echo $getPostCategoryLink ?>
							</span>
						</li>
						<li>本文标签：
							<?php echo $getPostTagLink ?>
						</li>
						<li>文章热度：<span id="post_view_count">
							<font color="red"><?php echo $post->getPostView(); ?> ℃</font></span> 
						</li>
						<li>生产时间：
							<?php echo $post->getPublishedDate() ?>
						</li>
					</ul>
					<ul class="entry-relate-links">
						<li>上一篇 &gt;：</span>
							<?php echo $post->getPreviousPost() ?>
						</li>
						<li>下一篇 &gt;：</span>
							<?php echo $post->getNextPost() ?>
						</li>
					</ul>
				</div>
			</div>
			<div class="post-bottom">
				<div class="post-bottom-title">
					<h5 class="border-left">相关文章</h5>
				</div>
				<ul class="related-post">
					<?php foreach ($post->getRelatedPost(8) as $postItem) { ?>
						<li>
							<a href="<?php echo $postItem->getPostUrl() ?>">
								<?php echo $postItem->getPostThumbnail(165, 105) ?>
							</a>
							<h4>
								<a href="<?php echo $postItem->getPostUrl() ?>">
									<?php echo $postItem->getPostTitle(20) ?>
								</a>
							</h4>
							<p><?php echo $postItem->getPostCategory() ?></p>
							<p><?php echo $postItem->getPostView() ?>℃</p>

						</li>
					<?php } ?>				
				</ul>
				<div class="clear"></div>
			</div>
			<?php //echo var_dump($post->getAbc()) ?>	
			<!-- <div id="post-comments">
			
			</div> -->				
		</article>
	</div>
	<!-- sidebar -->
	<aside class="sidebar">		
		<?php $this->partial("sidebar/sidebarB") ?>
	</aside>
	<!-- sidebar -->
	<div class="clear"></div>

</div>
<!--end main-->