<div class="am-cf am-padding">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">所有文章</strong></div>
</div>

<?php $this->flashSession->output(); ?>

<div class="am-g am-padding-horizontal-sm">
	<hr/>
    <div class="am-u-sm-12" id="post-list-content">
    	<?php foreach ($posts_list->items as $post_item) { ?>   
        
        <?php } ?>    	

    </div>

    <div class="am-cf am-padding-bottom post-list-next">
    	<hr/>
        <?php if (!empty($posts_list->next)) { ?>
            <a href="/manage/posts/index?page=<?php echo $posts_list->next ?>" current="<?php echo $posts_list->current ?>" last="<?php echo $posts_list->last ?>" class="am-btn am-btn-success am-btn-block">查看更多...</a>
        <?php } ?>
    </div>


    


</div>