<div class="am-cf am-padding" id="abcdef">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">媒体库</strong></div>
</div>
<div id="media-picture-list">
    <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-margin gallery-list" id="media-picture-list-ul">

        <?php foreach ($fileListPage->items as $picture) { ?>
            <li>
                <a>
                    <img class="am-img-thumbnail" src="<?php echo $picture->getThumbnail(720,500) ?>" width="720" height="500"/>
                </a>
            </li>
        <?php } ?>
          
    </ul>
    
    <div class="am-margin am-cf media-picture-next">
        <hr/>
        <?php   $currentPage = $fileListPage->current;
                $nextPage = $fileListPage->next;
                $lastPage = $fileListPage->last;

            if ($lastPage == $currentPage) {
                echo '<a href="#" class="am-btn am-btn-danger am-btn-block am-disabled">没有更多了！</a>';
            } else {
                echo $this->tag->linkTo(array('medialibrary/index?page='.$nextPage, '查看更多...', 'class' => 'am-btn am-btn-success am-btn-block', 'current' => $currentPage, 'last' => $lastPage));
            }
            ?>  
    </div>
</div>