<div class="am-cf am-padding" id="abcdef">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">媒体库</strong></div>
</div>
<div id="media-picture-list">
    <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-margin gallery-list" id="media-picture-list-ul">

        <?php foreach ($file_list_page->items as $picture) { ?>
            <li>
                <a>
                    <img class="am-img-thumbnail" src="<?php echo $picture->getThumbnail(720,500) ?>" width="720" height="500"/>
                </a>
            </li>
        <?php } ?>
          
    </ul>
    
    <div class="am-margin am-cf media-picture-next">
        <hr/>
        <?php if (!empty($file_list_page->next)) { ?>
            <a href="/manage/medialibrary/index?page=<?php echo $file_list_page->next ?>" current="<?php echo $file_list_page->current ?>" last="<?php echo $file_list_page->last ?>" class="am-btn am-btn-success am-btn-block">查看更多...</a>
        <?php } ?>
    </div>
</div>