<div id="post-picture-list">
	<ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-margin-sm gallery-list am-scrollable-vertical" id="post-picture-list-ul">

		<?php foreach ($fileListPage->items as $picture) { ?>
		    <li>
		        <a>
		            <img class="am-img-thumbnail" src="<?php echo $picture->getThumbnail(720,500) ?>" width="720" height="500" picture-url="<?php echo $picture->file_url ?>" picture-width="<?php echo $picture->image_width ?>" picture-height="<?php echo $picture->image_height ?>"/>
		        </a>
		    </li>
		<?php } ?>
		          
	</ul>
    
	<div class="am-margin-sm am-cf">
	<hr/>
		<div class="am-g">
			<div class="am-u-lg-4 am-u-md-4 am-u-sm-4">
				<a href=""class="am-btn am-btn-success am-btn-block am-btn-sm" id="post-picture-close">关闭</a>
			</div>
	  		<div class="am-u-lg-4 am-u-md-4 am-u-sm-4 post-picture-next">
	  			<?php  	$currentPage = $fileListPage->current;
	  					$nextPage = $fileListPage->next;
	  					$lastPage = $fileListPage->last;

	  				if ($lastPage == $currentPage) {
	  					echo '<a href="#" class="am-btn am-btn-danger am-btn-block am-disabled am-btn-sm">没有更多了！</a>';
	  				} else {
	  					echo $this->tag->linkTo(array('medialibrary/postaddpicture?page='.$nextPage, '查看更多...', 'class' => 'am-btn am-btn-success am-btn-block am-btn-sm', 'current' => $currentPage, 'last' => $lastPage));
	  				}
	  				?>
	  			
	  		</div>
	  		<div class="am-u-lg-4 am-u-md-4 am-u-sm-4">
	  			<a href=""class="am-btn am-btn-success am-btn-block am-btn-sm" id="post-picture-append">添加</a>
	  		</div>
	  	</div>
	</div>
</div>