<div class="am-cf am-padding">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">首页</strong></div>
</div>

<?php $this->flashSession->output(); ?>

<ul class="am-avg-sm-1 am-avg-md-4 am-margin am-padding am-text-center admin-content-list ">
    <li><a href="#" class="am-text-success"><span class="am-icon-btn am-icon-file-text"></span><br/>新增页面<br/>0</a></li>
    <li><a href="#" class="am-text-warning"><span class="am-icon-btn am-icon-briefcase"></span><br/>成交订单<br/>0</a></li>
    <li><a href="#" class="am-text-danger"><span class="am-icon-btn am-icon-recycle"></span><br/>昨日访问<br/>0</a></li>
    <li><a href="#" class="am-text-secondary"><span class="am-icon-btn am-icon-user-md"></span><br/>在线用户<br/>0</a></li>
</ul>

<?php 
    
    //if (isset($post_category)){
	//	var_dump($post_category); 
	//}
?>

<!-- <div id="my-content-body">
<?php 
	//获取url
	//echo $this->url->get("cities/get");
	//将文本转换为URL标题
 	//echo Phalcon\Tag::friendlyTitle('These are big important news', '-');

	

 ?>
 <?php $this->flashSession->output(); ?>

 	<?php 
    
    if (isset($post_category)){
		var_dump($post_category); 
	}
	//foreach ($post_category->postsTags as $robotPart) {
    //	echo $robotPart->posts->post_title, "\n";   
	//}

	//$robot = $post_category->getPostsTags();
	//$robot = $post_category->getPosts;

	//echo $robot；
	//var_dump($robot);

	//echo $robot->id;


	
	?>
</div> -->