<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<?php echo $this->tag->getTitle(); ?>
	<?php 
		if(!empty($pageDescription)) {
			echo '<meta name="description" content="'.$pageDescription.'" />';
		}
		if(!empty($pageKeywords)) {
			echo '<meta name="keywords" content="'.$pageKeywords.'" />';
		}
		?>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<meta http-equiv="Cache-Control" content="no-siteapp" />
	<meta name="apple-mobile-web-app-title" content="一刻" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <!-- 针对手持设备优化，主要是针对一些老的不识别viewport的浏览器，比如黑莓 -->
    <meta name="HandheldFriendly" content="true">
    <!-- uc强制竖屏 -->
    <meta name="screen-orientation" content="portrait">
    <!-- QQ强制竖屏 -->
    <meta name="x5-orientation" content="portrait">
    <!-- UC强制全屏 -->
    <!-- <meta name="full-screen" content="yes"> -->
    <!-- QQ强制全屏 -->
    <meta name="x5-fullscreen" content="true">
    <!-- UC应用模式 -->
    <!-- <meta name="browsermode" content="application"> -->
    <!-- QQ应用模式 -->
    <meta name="x5-page-mode" content="app">
    <!-- windows phone 点击无高光 -->
    <meta name="msapplication-tap-highlight" content="no">
	<link rel="icon" href="http://c8023.com/favicon/favicon.ico" type="image/x-icon">
	<?php echo $this->tag->stylesheetLink('wap/css/style.css'); ?>
	<?php echo $this->tag->stylesheetLink('wap/css/main.css'); ?>
	<?php echo $this->tag->stylesheetLink('common/Font-Awesome/css/font-awesome.css'); ?>
</head>
<body>
<!-- <header id="nav">
	
</header>  -->

<div class="container">

	<?php echo $this->getContent(); ?>

</div>
<!-- #container -->

<!-- <footer id="footer">
	<div id="footer-body">
		<div id="footer-content">
			Copyright &copy; <?php echo date('Y'); ?> <a href="<?php echo APP_URL ?>" rel="home"><?php //bloginfo( 'name' ); ?></a>
		</div>
	</div>
</footer> -->

<nav class="bottom-nav">
	<ul class="bottom-nav-ul">
		<li class="bottom-nav-ul-li"><a href="<?php echo APP_URL ?>">首页</a></li>
		<li class="bottom-nav-ul-li">
			<a href="#" class="submenu">分类</a>
			<div class="bottom-nav-explor bottom-nav-cat">
				<ul class="cat_ul">
					<?php foreach($categorys->getCategorys() as $category ) { 
						echo '<li>'.$category.'</li>';
						} ?>
				</ul>
			</div>
		</li>
		<li class="bottom-nav-ul-li">
			<a href="#" class="submenu">标签</a>
			<div class="bottom-nav-explor bottom-nav-tag">
				<?php foreach($tags->getTags() as $tag ) { 
						echo $tag;
					} ?>
			</div>
		</li>
		<li class="bottom-nav-ul-li">
			<a href="#" class="submenu">更多</a>
			<div class="bottom-nav-explor bottom-nav-more">
				<a href="<?php //echo home_url( '/' ); ?>about">关于我们</a>
				<a href="<?php //echo home_url( '/' ); ?>sitemap.html">站点地图</a>
			</div>
		</li>
		<li class="bottom-nav-ul-li">
			<a href="#" class="submenu">搜索</a>
			<div class="bottom-nav-explor bottom-nav-search"></div>
		</li>
	</ul>
</nav>

<?php echo $this->tag->javascriptInclude('wap/script/jquery.min.js'); ?>
<?php echo $this->tag->javascriptInclude('wap/script/mobile.js'); ?>

</body>
</html>