<?php echo $this->tag->form(array("types/index", "id" => "add-type-form", "class" => "am-form am-g am-g-collapse")) ?>			
	<legend class="am-text-lg">添加</legend>

	<div class="am-form-group am-hide">
		<label for="doc-ipt-id-1">ID</label>
		<?php echo $this->tag->textField(array("typeId", "class" => "form-control", "placeholder" => "ID")); ?>
	</div>

	<div class="am-form-group">
		<label for="doc-ipt-pwd-1">名称</label>
		<?php echo $this->tag->textField(array("typeTitle", "class" => "form-control", "placeholder" => "名称……", "autofocus" => "true")); ?>
	</div>

	<div class="am-form-group">
		<label for="doc-ipt-pwd-1">描述</label>
		<?php echo $this->tag->textArea(array("typeDescription", "rows" => 3, "class" => "form-control", "placeholder" => "描述……")); ?>
	</div>

	<div class="am-form-group">
		<a class="am-btn am-btn-success am-btn-block" id="add-type-submitform" href="#"><i class="am-icon-paper-plane"></i>  提交</a>
	</div>
		    
</form>