<div class="am-cf am-padding">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">500</strong></div>
</div>

<div class="am-g">
    <div class="am-u-sm-12">
        <h2 class="am-text-center am-text-xxxl am-margin-top-lg">500. SERVER ERROR</h2>
        <p class="am-text-center">服务器内部错误</p>
        <pre class="page-404">
          .----.
       _.'__    `.
   .--($)($$)---/#\
 .' @          /###\
 :         ,   #####
  `-..__.-' _.-\###/
        `;_:    `"'
      .'"""""`.
     /,  ya ,\\
    //  500!  \\
    `-._______.-'
    ___`. | .'___
   (______|______)
        </pre>
    </div>
</div>