<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php echo $this->tag->getTitle(); ?>
    <meta name="description" content="一刻-内容管理系统">
    <meta name="keywords" content="一刻">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="icon" type="image/png" href="/static/manage/assets/i/favicon.png">
    <link rel="apple-touch-icon-precomposed" href="/static/manage/assets/i/app-icon72x72@2x.png">
    <meta name="apple-mobile-web-app-title" content="一刻" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <!-- 针对手持设备优化，主要是针对一些老的不识别viewport的浏览器，比如黑莓 -->
    <meta name="HandheldFriendly" content="true">
    <!-- uc强制竖屏 -->
    <meta name="screen-orientation" content="portrait">
    <!-- QQ强制竖屏 -->
    <meta name="x5-orientation" content="portrait">
    <!-- UC强制全屏 -->
    <!-- <meta name="full-screen" content="yes"> -->
    <!-- QQ强制全屏 -->
    <meta name="x5-fullscreen" content="true">
    <!-- UC应用模式 -->
    <!-- <meta name="browsermode" content="application"> -->
    <!-- QQ应用模式 -->
    <meta name="x5-page-mode" content="app">
    <!-- windows phone 点击无高光 -->
    <meta name="msapplication-tap-highlight" content="no">

    <?php echo $this->tag->stylesheetLink('manage/assets/css/amazeui.css'); ?>
    <?php echo $this->tag->stylesheetLink('manage/simditor/styles/simditor.css'); ?>
    <?php echo $this->tag->stylesheetLink('manage/dropzone/dropzone.css'); ?>
    <?php echo $this->tag->stylesheetLink('manage/sweetalert/sweet-alert.css'); ?>
    <?php echo $this->tag->stylesheetLink('manage/assets/css/admin.css'); ?>
    <?php echo $this->tag->stylesheetLink('manage/assets/css/app.css'); ?>
    
</head>
<body>
<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器，Amaze UI 暂不支持。 请 <a href="http://browsehappy.com/" target="_blank">升级浏览器</a>
  以获得更好的体验！</p>
<![endif]-->

<header class="am-topbar admin-header">
    <div class="am-topbar-brand">
        <strong>一刻 </strong> <small>后台管理系统</small>
    </div>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only" data-am-collapse="{target: '#topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span class="am-icon-bars"></span></button>

    <div class="am-collapse am-topbar-collapse" id="topbar-collapse">
        <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
            <li><a href="javascript:;"><span class="am-icon-envelope-o"></span> 收件箱 <span class="am-badge am-badge-warning">5</span></a></li>
            <li class="am-dropdown" data-am-dropdown>
                <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
                    <span class="am-icon-users"></span> <?php echo $name; ?> <span class="am-icon-caret-down"></span>
                </a>
                <ul class="am-dropdown-content">
                    <li><a href="#"><span class="am-icon-user"></span> 资料</a></li>
                    <li><a href="#"><span class="am-icon-cog"></span> 设置</a></li>
                    <li><a href="<?php echo $this->url->get('session/logout'); ?>"><span class="am-icon-power-off"></span> 退出</a></li>
                </ul>
            </li>
            <li class="am-hide-sm-only"><a href="javascript:;" id="admin-fullscreen"><span class="am-icon-arrows-alt"></span> <span class="admin-fullText">开启全屏</span></a></li>
        </ul>
    </div>
</header>

<div class="am-cf admin-main">
    <!-- sidebar start -->
    <div class="admin-sidebar am-offcanvas" id="admin-offcanvas">
        <div class="am-offcanvas-bar admin-offcanvas-bar">
            
            <?php echo $this->elements->getSidebarMenu(); ?>
            
            <div class="am-panel am-panel-default admin-sidebar-panel">
                <div class="am-panel-bd">
                    <p><span class="am-icon-bookmark"></span> 公告</p>
                    <p>时光静好，与君语；细水流年，与君同。</p>
                </div>
            </div>
            
            <div class="am-panel am-panel-default admin-sidebar-panel">
                <div class="am-panel-bd">
                    <p><span class="am-icon-tag"></span> wiki</p>
                    <p>Welcome to the EVEVCASE!</p>
                </div>
            </div>
    
        </div>
    </div>
  <!-- sidebar end -->

  <!-- content start -->
    <div class="admin-content">

        <?php echo $this->getContent(); ?>
        
    </div>
  <!-- content end -->

</div>

<a class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu" data-am-offcanvas="{target: '#admin-offcanvas'}"></a>

<footer>
    <hr>
    <p class="am-padding-left">© 2015 一刻</p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<?php echo $this->tag->javascriptInclude('manage/assets/js/polyfill/rem.min.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/assets/js/polyfill/respond.min.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/assets/js/amazeui.legacy.js'); ?>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<?php echo $this->tag->javascriptInclude('manage/assets/js/jquery.min.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/assets/js/amazeui.min.js'); ?>
<!--<![endif]-->
<?php echo $this->tag->javascriptInclude('manage/simditor/scripts/module.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/simditor/scripts/hotkeys.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/simditor/scripts/uploader.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/simditor/scripts/simditor.js'); ?>
<!--<?php echo $this->tag->javascriptInclude('manage/simditor/scripts/simditor-autosave.js'); ?>-->
<?php echo $this->tag->javascriptInclude('manage/simditor/scripts/simditor-dropzone.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/dropzone/dropzone.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/sweetalert/sweet-alert.min.js'); ?>
<?php echo $this->tag->javascriptInclude('manage/assets/js/app.js'); ?>
    <script type="text/javascript">
        $(document).ready(function(){
            $.AMUI.progress.start();
        });        
        $(window).load(function(){
            $.AMUI.progress.done();
        });
    </script>
</body>
</html>