<div class="main" id="main">
	<div class="content">
		<div class="home-content">
			<!-- postList -->
			<?php $this->partial("postList/postListA") ?>
			<!-- postList -->
			<!-- postNav -->
			<?php echo $this->elements->getNav($posts_list); ?>
			<!-- postNav -->
		</div>
	</div>
	<!-- sidebar -->
	<aside class="sidebar">
		<?php $this->partial("sidebar/sidebarA") ?>
	</aside>
	<!-- sidebar -->
	<div class="clear"></div>

</div>
<!--end main-->	