<div class="am-cf am-padding">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">标签</strong></div>
</div>

<?php $this->flashSession->output(); ?>

<div class="am-cf am-g">
	<div class="am-u-lg-4" id="tag-form">
		<!--tagform-->
	</div>
  	<div class="am-u-lg-8">
  		<legend class="am-text-lg">列表</legend>
  		<div class="am-cf am-g">
			<div class="am-u-lg-1 am-show-lg-only"><strong>ID</strong></div>
			<div class="am-u-lg-2 am-u-md-6 am-u-sm-6"><strong>标签</strong></div>
			<div class="am-u-lg-6 am-show-lg-only"><strong>描述</strong></div>
			<div class="am-u-lg-3 am-u-md-6 am-u-sm-6"><strong>操作</strong></div>
  		</div>
  		<hr/>
		<div id="tag-list">
	  		 <!--taglist--> 		
  		</div>
  	</div>
</div>
