<div id="content">
	<?php $post->setPostView() ?>
		<div class="post-title post-title-background">
			<h1>
				<?php echo $post->getPostTitle(50) ?>
			</h1>
			<div class="post-title-detail">
				<span><i class="fa fa-th fa-fw"></i><?php echo $post->getPostCategoryLink() ?></span>
				<span><?php echo $post->getPostView() ?>℃</span>
				<span><?php echo $post->getPublishedDate() ?></span>
			</div>
		</div>
		<div class="post-content">
			<?php echo $post->getContent() ?>
		</div>
		<div class="clear"></div>
		<div class="post-bottom">
			<div class="section-title post-title-background">关于本文</div>
			<div class="post-detail">
				<ul>
					<li>属于分类：<span id="post_category"><?php echo $post->getPostTagLink() ?></li>
					<li>本文标签：<?php echo $post->getPostCategoryLink() ?></li>
					<li>流行热度：<span id="post_view_count">超过  <?php echo $post->getPostView(); ?> 次浏览</span></li>
					<li>生产日期：<?php echo $post->getPublishedDate() ?></li>
				</ul>
				<ul class="entry-relate-links">
					<li><span class="muted"><i class="icon-chevron-up"></i> 上一篇 &gt;：</span>
						<a href="<?php if ($post->getPreviousPost()) { echo $post->getPreviousPost()->getPostUrl(); } else { echo "javascript:alert('木有啦，已经是最后一篇了...');"; } ?>">
							<?php if ($post->getPreviousPost()) { echo $post->getPreviousPost()->getPostTitle(); } else { echo "木有啦！！！"; } ?></a>
					</li>
					<li><span class="muted"><i class="icon-chevron-down"></i> 下一篇 &gt;：</span>
						<a href="<?php if ($post->getNextPost()) { echo $post->getNextPost()->getPostUrl(); } else { echo "javascript:alert('木有啦，已经是最后一篇了...');"; } ?>">
							<?php if ($post->getNextPost()) { echo $post->getNextPost()->getPostTitle(); } else { echo "木有啦！！！"; } ?></a>
					</li>
				</ul>
				<ul class="prev-next-post">
					<?php if ($post->getPreviousPost()) { ?>
						<a href="<?php echo $post->getPreviousPost()->getPostUrl() ?>" class="prev">上一篇文章</a>
					<?php } ?>
					<?php if ($post->getNextPost()) { ?>
						<a href="<?php echo $post->getNextPost()->getPostUrl() ?>">下一篇文章</a>
					<?php } ?>
				</ul>
			</div>
		</div>
		
		<div class="post-bottom">
			<div class="section-title post-title-background">相关文章</div>
			<div class="related-post-container">
				<?php 
					foreach ($post->getRelatedPost() as $postItem) {
						$this->partial("postList/relatedPostA");
					}
					?>
			</div>
		</div>

		<div class="post-footer"></div>

</div>